User manager impl
saltedfishclub/PolarCore pull request #49
Opened 2021-08-06 14:31 UTC by EvanLuo42

2021-08-06 14:33 UTC, EvanLuo42 commented
@iceBear67

2021-08-07 05:25 UTC, EvanLuo42 commented
Fuck

2021-08-07 05:28 UTC, iceBear67 commented
?

2021-08-07 05:31 UTC, iceBear67 commented
Did you fix that table creation problem?  
Or you'll have to submit another PR for that

2021-08-12 07:51 UTC, iceBear67 requested changes
Table creation.

2021-11-06 02:14 UTC, closed without merging